variables:
  OSDU_GCP_SERVICE: odatadms
  OSDU_GCP_VENDOR: gcp

osdu-gcp-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE

osdu-gcp-dev2-test:
  variables:
    STORAGE_BASE_URL: $OSDU_GCP_STORAGE_EXTERNAL_URL
    LEGAL_BASE_URL: $OSDU_GCP_LEGAL_EXTERNAL_URL
    DATASET_BASE_URL: $OSDU_GCP_DATASET_EXTERNAL_URL
    SCHEMA_API: $OSDU_GCP_SCHEMA_URL
    PROVIDER_KEY: GCP
    KIND_SUBTYPE: DatasetTest
    LEGAL_TAG: datatest-int-tag
    LEGAL_HOST: $OSDU_GCP_LEGAL_EXTERNAL_URL
    GCP_STORAGE_PERSISTENT_AREA: persistent-area
    GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE
